name: testingflutterapp
description: kidskeeper app for parents
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.0.3
  google_maps_flutter: ^0.5.27+2
  sqflite: ^1.3.1
  http: ^0.12.2
  sliding_up_panel: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - image/KIKI.png
    - image/CCTV.png
    - image/CCTVButton.png
    - image/kidLocation.png
  fonts:
    - family: BMJUA
      fonts:
        - asset: fonts/BMJUA_ttf.ttf

